---
- hosts: k8s_cluster
  become: yes
  tasks:
    - name: Install necessary dependencies
      yum:
        name: ['python3', 'python3-pip', 'epel-release', 'ansible', 'net-tools', 'bind-utils', 'wget', 'yum-utils', 'device-mapper-persistent-data', 'lvm2']
        state: present

    - name: Add Kubernetes repository
      get_url:
        url: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        dest: /etc/yum.repos.d/kubernetes.repo
        mode: '0644'

    - name: Install Kubernetes
      yum:
        name: ['kubelet', 'kubeadm', 'kubectl']
        state: present
      notify: Start kubelet

    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

  handlers:
    - name: Start kubelet
      systemd:
        name: kubelet
        state: started
        enabled: yes
...
